// Generated by LiveScript 1.5.0
(function(){
  var createServer, chalk, middleware, main, out$ = typeof exports != 'undefined' && exports || this;
  createServer = require('http').createServer;
  chalk = require('chalk');
  middleware = function(req, res){
    console.log('Ho a request!');
    console.log(chalk.yellow(req.url, req.method));
    res.write('Ok Bitcj ?');
    return res.end();
  };
  out$.main = main = function(args, argv){
    return createServer(middleware).listen(4545, function(){
      console.log('Server running');
    });
  };
}).call(this);
