// Generated by LiveScript 1.5.0
(function(){
  var test, main;
  test = require('tape').test;
  main = require('./Main').main;
  test('Main :: does nothing', function(arg$){
    var equal, end;
    equal = arg$.equal, end = arg$.end;
    equal(true, true);
    return end();
  });
}).call(this);
